In [5]:
# 単位行列

import numpy as np

print(np.eye(2))

print(np.eye(3))


[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 逆行列の行列式

import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.det(a))

b = np.array([[1, 2],
              [0, 0]])
print(np.linalg.det(b))

-2.0000000000000004
0.0


In [9]:
# 逆行列

import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
#　練習問題

import numpy as np

a = np.array([[1, 1],
              [1, 2]])
# 行列式
print(np.linalg.det(a))

# 逆行列
print(np.linalg.inv(a))


1.0
[[ 2. -1.]
 [-1.  1.]]
