In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])
b = np.array([[2, 1],
             [2, 1],
             [2, 1]])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [5]:
# 　要素ごとの積
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]])
print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [6]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])
b = np.array([[0, 1],
              [1, 2],
              [2, 3]])
# 行列積
print(np.dot(a, b))


c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]])
# 要素ごとの積
print(c*d)



[[ 5  8]
 [ 8 14]]
[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
