In [4]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[5, 4, 3], [2, 1, 0]])

print(a + b)
print()
print(a - b)
print()
print(a * b)


[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
