In [2]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5

In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])
print(b)

[1 2 3]
[-2.3   0.25 -1.2   1.8   0.41]


In [9]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(a)

b= np. array([[0.21, 0.14],
             [-1.3, 0.8],
             [0.12, -2.1]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.8 ]
 [ 0.12 -2.1 ]]


In [12]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
               [2, 3, 4, 5],
               [4, 5, 6, 7]],
              
              [[1, 2, 3, 4],
              [3, 4, 5, 6],
              [5, 6, 7, 8]]])  #(2,3,4)の３階のテンソル
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


In [18]:
import numpy as np

a = np.array(1)
print(a)
print()

b = np.array([1, 2, 3, 4])
print(b)
print()

c = np.array([[4, 5, 6, 7],
             [7, 6, 5, 4]])
print(c)
print()
              
d = np.array([[[1, 2, 3, 4],
               [2, 3, 4, 5],
               [6, 7, 8, 9]],
              [[2, 3, 4, 5],
               [6, 7, 8, 9],
               [3, 4, 5, 6]]])
print(d)
             

1

[1 2 3 4]

[[4 5 6 7]
 [7 6 5 4]]

[[[1 2 3 4]
  [2 3 4 5]
  [6 7 8 9]]

 [[2 3 4 5]
  [6 7 8 9]
  [3 4 5 6]]]
