In [1]:
import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]])
print(a.T)  #転置

[[1 4]
 [2 5]
 [3 6]]


In [3]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# print(np.dot(a, b))

print(np.dot(a, b.T))

[[14 32]
 [32 77]]


In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]])
b = np.array([[0, 1, 2],
              [1, 3, 4]])

# 行列積
print(np.dot(a.T, b))
print()
print(np.dot(a, b.T))


[[ 5 11]
 [ 8 19]]
